mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:category_id>', views.products, name='category'),
    path('products/', views.products, name='products'),
    path('basket-add/<int:product_id>', views.basket_add, name='basket_add'),  # <int:...> должен совпадать с тем, что мы передаём в контроллере(вьюхе)
    path('basket-delete/<int:id>', views.basket_delete, name='basket_delete'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
]

products/models.py
from django.db import models
from users.models import User


# после создания новой модели и миграции не стоит забывать регистрировать её в admin.py
class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "Product Categories"  # Как будет выглядеть в о множественном числе (в админке)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)  # типа колличество на складе
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)  # связь многие к одному, on_delete - параметр решающий что делать с продуктами,если удалиться вся категория(ProductCategory)

    def __str__(self):
        return f"{self.name} | {self.category.name}"


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)  # мы щас не используем, но в будущем они будут важны, чтобы узнать когда добавился например объект
    modified_timestamp = models.DateTimeField(auto_now_add=True)  # auto_now_add те автоматически добавляются сами

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

class MyModel(models.Model):
    data = models.JSONField()

    def __str__(self):
        return str(self.data)

products/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from products.models import ProductCategory, Product, Basket


def index(request):
    context = {
        'title': 'magaz'
    }
    return render(request, 'products/index.html', context)


def products(request, category_id=None):
    context = {'title': 'каталог', 'categories': ProductCategory.objects.all()}
    if category_id:  # пришёл ли айдишник категории, это для того чтобы работали категории
        product_list = Product.objects.filter(category_id=category_id)
    else:
        product_list = Product.objects.all()

    paginator = Paginator(product_list, 4)  # Показывать 4 продуктов на странице
    page_number = request.GET.get('page')

    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context.update({'products': page_obj})

    return render(request, 'products/products.html', context)


@login_required
def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)  # какой продукт мы хотим добавить
    baskets = Basket.objects.filter(user=request.user, product=product)  # список всех элементов корзины (но там всего 1 элемент)

    if not baskets.exists():  # если не существует
        Basket.objects.create(user=request.user, product=product,
                              quantity=1)  # объект только создан, поэтому колличество его 1
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()  # first() - берет первый элемент списка
        basket.quantity += 1
        basket.save()  # save() и create() выполняют одну и ту же функцию
        return HttpResponseRedirect(current_page)

@login_required
def basket_delete(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'products:index' %}">Koteyko</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:products' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {#                <li class="nav-item">#}
                {#                    <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>#}
                {#                </li>#}
                <li class="nav-item dropdown">
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                       data-bs-toggle="dropdown" aria-expanded="false">#}
{#                        <i class="fas fa-user-circle"></i>#}
{#                    </a>#}
{#                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">#}
                        <li>
                            <a class="nav-link" href="{% url 'users:profile' %}">Профиль <i class="fas fa-user-circle"></i></a>
                        </li>
{#                        <li><a class="dropdown-item" href="admin/admin.html">Админ-панель</a></li>#}
                        <li><a class="nav-link" href="admin/">Админка</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% if user.is_authenticated %}
                            <li>
                                <a class="nav-link" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Войти <i
                                        class="fas fa-sign-in-alt"></i></a>
                            </li>
                        {% endif %}
{#                    </ul>#}
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

products/templates/products/basket.html
{% if baskets %}
    <div class="col-lg-5">
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
    </h4>
        {% for basket in baskets %}
            <div class="card mb-3">
        <div class="card-body">
            <h5 class="card-title">{{ basket.product.name }}</h5>
            <p class="card-text">{{ basket.product.short_description }}</p>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item bg-light">
                <div class="row text-center">
                    <div class="col-lg-4">
                        <span class="text-muted">{{ basket.quantity }} шт.</span>
                        <a href="{% url 'products:basket_add' basket.product_id %}">
                            <i class="fas fa-cart-plus"></i>
                        </a>
{#                        <input name="basketID" type="number" class="form-control"#}
{#                               value="{{ basket.quantity }}" min="0">#}
                    </div>
                    <div class="col-lg-4">{{ basket.sum }} руб.</div>  {# вызвал метод из моделс, но в шаблонах можно вызывать только методы без аргументов, для того, чтобы мы не перегружали наш шаблон #}
                    <div class="col-lg-4">
                        <a href="{% url 'products:basket_delete' basket.id %}">
                            <i class="fas fa-trash"></i>
                        </a>
                    </div>
                </div>
            </li>
        </ul>
    </div>
        {% endfor %}

    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ total_sum }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/checkout_order.html">
        Оформить заказ
    </a>
</div>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Koteyko  Store</h1>
                <p>
                    Что вы знаете о кошачем стиле?
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:products' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}


{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">CatShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"
                           class="list-group-item">
                            {{ category.name }}
                        </a>
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/koteyko1.jpg' %}"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/koteyko2.jpg' %}"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'vendor/img/slides/koteyko3.jpg' %}"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="/media/{{ product.image }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб</h5>
                                    <p class="card-text">{{ product.short_description }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'products:basket_add' product.id %}">
                                        <button type="button" class="btn btn-outline-success">
                                            Отправить в корзину
                                        </button>
                                    </a>


                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if products.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">&laquo; first</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.previous_page_number }}">previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">&laquo; first</span>
                            </li>
                            <li class="page-item disabled">
                                <span class="page-link">previous</span>
                            </li>
                        {% endif %}

                        <li class="page-item active">
                            <span class="page-link">
                                Page {{ products.number }} of {{ products.paginator.num_pages }}
                            </span>
                        </li>

                        {% if products.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.next_page_number }}">next</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <span class="page-link">next</span>
                            </li>
                            <li class="page-item disabled">
                                <span class="page-link">last &raquo;</span>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Это низ страницы</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}

products/templates/products/test-context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|title }}</title>
</head>
<body>
<h1>{{ header }}</h1>
<p>{{ username }}</p>
{% for product in products %}
    <h4>{{ product.name }}</h4>
    <h4>{{ product.price }}</h4>
{% endfor %}
{% if promotion %}
    <h3 style="color: red;">Товары по акции:</h3>
    {% for product in products_of_promotion %}
    <h4>{{ product.name }}</h4>
    <h4>{{ product.price }}</h4>
    {% endfor %}
{% endif %}
</body>
</html>